services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile_development
    command: bash -c "yarn install --ignore-engines && rm -f tmp/pids/server.pid && ./bin/server"
    stdin_open: true
    ports:
      - '5000:5000'
      - '3035:3035'
    env_file: production.env
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
      DB_HOST: host.docker.internal
      DB_USERNAME: root
      DB_PASSWORD: ''
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - gem_data:/usr/local/bundle
      - /var/tmp

volumes:
  gem_data:
  node_modules:
